# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

# Catppuccin Mocha
#
# gui:
#   theme:
#     activeBorderColor:
#       - '#89b4fa'
#       - bold
#     inactiveBorderColor:
#       - '#a6adc8'
#     optionsTextColor:
#       - '#89b4fa'
#     selectedLineBgColor:
#       - '#313244'
#     cherryPickedCommitBgColor:
#       - '#45475a'
#     cherryPickedCommitFgColor:
#       - '#89b4fa'
#     unstagedChangesColor:
#       - '#f38ba8'
#     defaultFgColor:
#       - '#cdd6f4'
#     searchingActiveBorderColor:
#       - '#f9e2af'
#
#   authorColors:
#     '*': '#b4befe'

gui:
  theme:
    activeBorderColor:
      - '#7E9CD8'  # crystalBlue - for active borders
      - bold
    inactiveBorderColor:
      - '#727169'  # fujiGray - for inactive borders
    optionsTextColor:
      - '#7E9CD8'  # crystalBlue - for option text highlights
    selectedLineBgColor:
      - '#363646'  # sumiInk3 - for selected line backgrounds
    cherryPickedCommitBgColor:
      - '#2A2A37'  # sumiInk2 - for cherry-picked commit backgrounds
    cherryPickedCommitFgColor:
      - '#7E9CD8'  # crystalBlue - for cherry-picked commit text
    unstagedChangesColor:
      - '#C34043'  # autumnRed - for unstaged changes
    defaultFgColor:
      - '#DCD7BA'  # fujiWhite - for default text
    searchingActiveBorderColor:
      - '#E6C384'  # carpYellow - for search highlights
  authorColors:
    '*': '#957FB8'  # oniViolet - for author names

