# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  theme:
    activeBorderColor:
      - '#fabd2f'  # Gruvbox Yellow
      - bold
    inactiveBorderColor:
      - '#7c6f64'  # Gruvbox Gray
    optionsTextColor:
      - '#d79921'  # Gruvbox Orange
    selectedLineBgColor:
      - '#32302f'  # Gruvbox Darker Background
    cherryPickedCommitBgColor:
      - '#504945'  # Gruvbox Selection Color
    cherryPickedCommitFgColor:
      - '#fabd2f'  # Gruvbox Yellow
    unstagedChangesColor:
      - '#fb4934'  # Gruvbox Red
    defaultFgColor:
      - '#ebdbb2'  # Gruvbox Foreground
    searchingActiveBorderColor:
      - '#d79921'  # Gruvbox Orange

  authorColors:
    '*': '#b8bb26'  # Gruvbox Green

