#!/bin/bash

red="0xffcc241d"
blue="0xff458588"
orange="0xffd65d0e"
green="0xff98971a"
yellow="0xffd79921"
purple="0xffb16286"
aqua="0xff689d6a"
gray="0xff504945"
transparent="0x00000000"

options=(
	style=round # round, square, or uniform
	width=5.5
	hidpi=on	
  	active_color="$red"
  	inactive_color="$gray"
  	blacklist="Screen Studio"
)

borders "${options[@]}"