return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "go",
      "gomod",
      "gosum",
      "gowork",
      "json",
      "javascript",
      "typescript",
      "tsx",
      "yaml",
      "html",
      "css",
      "prisma",
      "markdown",
      "markdown_inline",
      "svelte",
      "graphql",
      "bash",
      "fish",
      "lua",
      "vim",
      "dockerfile",
      "gitignore",
      "python",
      "sql",
      "toml",
      "xml",
      "query",
      "regex",
    },
  },
}
