#!/usr/bin/env sh

# ██╗   ██╗ █████╗ ██████╗  █████╗ ██╗
# ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗██║
#  ╚████╔╝ ███████║██████╔╝███████║██║
#   ╚██╔╝  ██╔══██║██╔══██╗██╔══██║██║
#    ██║   ██║  ██║██████╔╝██║  ██║██║
#    ╚═╝   ╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝
# A tiling window manager for macOS
# https://github.com/koekeishiya/yabai

# default layout (can be bsp, stack or float)
yabai -m config layout bsp
yabai -m config auto_balance on

# new window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding set to 12px
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

# -- mouse settings --

# center mouse on window with focus
yabai -m config mouse_follows_focus off

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap

# apps to not manage (ignore)
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Contacts$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Creative Cloud$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^OpenVPN Connect$" manage=off
yabai -m rule --add app="^Docker Desktop$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="^CleanMyMac X$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off

